version: 2.1

orbs:
  ruby: circleci/ruby@2.7.0
  heroku: circleci/heroku@1.2.3


jobs:
  build:
    docker:
    - image: circleci/ruby:2.7-node
      environment:
        BUNDLER_VERSION: 2.0.2
        RAILS_ENV: 'test'
    working_directory: ~/ExplanatoryApps
    steps:
      - checkout:
        path: ~/ExplanatoryApps
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.7-node
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
          MYSQL_ROOT_HOST: '127.0.0.1'
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      RAILS_ENV: test
    working_directory: ~/ExplanatoryApps
    steps:
      - checkout:
        path: ~/ExplanatoryApps
      - ruby/install-deps
      - run:
        name: Database Setup
        command: bundle exec rails db:migrate
      - run:
        name: Rspec
        command: 
          mkdir /tmp/test-results
          TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | \
            circleci tests split --split-by=timings)"

          bundle exec rspec \
            --format progress \
            --format RspecJunitFormatter \
            --out /tmp/test-results/rspec.xml \
            --format progress \
            $TEST_FILES

  deploy:
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - heroku/install
      - run:
          name: heroku login
          command: heroku container:login
      - run:
          name: push docker image
          command: heroku container:push web -a $HEROKU_APP_NAME
      - run:
          name: release docker image
          command: heroku container:release web -a $HEROKU_APP_NAME
      - run:
          name: database setup
          command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

  workflows:
    version: 2
    build_test_and_deploy:
      jobs:
        - build
        - test:
            requires:
              - build
        - deploy:
            requires:
              - test
            filters:
              branches:
                only: main 