apiVersion: batch/v1
kind: Job
metadata:
  name: db-seed
spec:
  template:
    spec:
      containers:
        - name: seed
          image: 599533428873.dkr.ecr.ap-northeast-1.amazonaws.com/hardening-lecture-app:latest
          command: ["bundle", "exec", "rails", "db:seed"]
          env:
            - name: RAILS_ENV
              value: development
            - name: DB_HOST
              value: db
      restartPolicy: Never
  backoffLimit: 0
