apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: web
    spec:
      initContainers:
        - name: dbcreate
          image: 599533428873.dkr.ecr.ap-northeast-1.amazonaws.com/hardening-lecture-app:latest
          command: ["bundle", "exec", "rails", "db:create"]
          env:
            - name: RAILS_ENV
              value: development
            - name: DB_HOST
              value: db
        - name: migrate
          image: 599533428873.dkr.ecr.ap-northeast-1.amazonaws.com/hardening-lecture-app:latest
          command: ["bundle", "exec", "rails", "db:migrate"]
          env:
            - name: RAILS_ENV
              value: development
            - name: DB_HOST
              value: db
        - name: seed
          image: 599533428873.dkr.ecr.ap-northeast-1.amazonaws.com/hardening-lecture-app:latest
          command: ["bundle", "exec", "rails", "db:seed"]
          env:
            - name: RAILS_ENV
              value: development
            - name: DB_HOST
              value: db
      containers:
        - command: ["bundle", "exec", "rails", "s", "-b", "0.0.0.0"]
          env:
            - name: RAILS_ENV
              value: development
            - name: DB_HOST
              value: db
          image: 599533428873.dkr.ecr.ap-northeast-1.amazonaws.com/hardening-lecture-app:latest
          imagePullPolicy: Always
          name: web
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: 250Mi
              cpu: 200m
      restartPolicy: Always
status: {}
